### PR TITLE
Add support for multiplot options

### PR DESCRIPTION
**Pull request by tomwhatmore**
I re-implemented the multiplot options from pull request #47 using @SiegeLord's feedback on the API and where to generate the gnuplot commands. I also added an example showing how to use the new options.

### CODE REVIEW

**Comment by SiegeLord** [comment]
Thanks! This looks better. I'll need to test things out more, but I'll start with this baseline. In particular, it's odd to me that some things are tied to the multi-layout which don't have to be (like title). I want to revisit whether we can always call `set multiplot`... it seems I disabled this in 2416ef81249e251fa051c40a8cd172129ff7a3fc for animation support, but I'm not completely sure why I did that.

**Comment by tomwhatmore** [comment]
I also felt like there was some weird over-coupling with the multi-layout logic, but I deliberately avoided getting into the larger questions of where and when the project calls ```set multiplot``` because it seemed out of scope for this feature, and additionally I didn't feel like I fully understood the existing logic. Just adding the extra options to the existing call seemed much safer!

Not sure how much I can help with any larger refactoring, but if I can make any changes to this PR that would make it easier let me know.

**Comment by SiegeLord** [comment]
A small update on this. It appears to not be a problem to just use `set multiplot` all the time. A bigger problem is the code right now calls `reset` before every axis, which nukes the multiplot options and breaks the `multiplot_options` example. Removing `reset` makes things like X-labels etc bleed across plots. Fixing #40 will remove the need to call `reset`, but that's a somewhat big effort.

**Comment by SiegeLord** [comment]
I've merged this with a number of supporting changes, thanks for the initial work!

**Pull request closed without merging**
