### PR TITLE
Specify desired the style using .editorconfig

### PR DESCRIPTION
**Pull request by Chris00**
Since this project [uses TABs](https://github.com/rust-lang/fmt-rfcs/issues/1#issuecomment-288847963), an [`.editorconfig`](https://editorconfig.org/) file may make the life of users easier.

### CODE REVIEW

**Comment by Chris00** [comment]
@SiegeLord How about this?  This repo does not follow the [standard formatting conventions](https://doc.rust-lang.org/beta/style-guide/index.html), so it would be nice to let the contributors know — and this is the easiest IMHO as most editors will automatically pick `.editorconfig`.

**Comment by SiegeLord** [comment]
The style is already described by `rustmt.toml`, I'd recommend having your editor evoke `cargo fmt` on save (or manually call `cargo fmt`).

**Comment by Chris00** [comment]
>  I'd recommend having your editor evoke cargo fmt on save 

Yes, I should do that — at least when a `rustfmt.toml` is present.  

I've cleaned up `rustfmt` configuration (it was generating warnings on nightly) and ran it.

**Comment by Chris00** [comment]
> Yes, I should do that — at least when a rustfmt.toml is present.

I've done so.  😀

**Comment by SiegeLord** [comment]
Thanks!

**Pull request merged**
